insert into artists (cus_event_id, name) values (1, 'parallelism');
insert into artists (cus_event_id, name) values (2, 'software');
insert into artists (cus_event_id, name) values (3, 'Seamless');
insert into artists (cus_event_id, name) values (4, 'support');
insert into artists (cus_event_id, name) values (4, 'Upgradable');
insert into artists (cus_event_id, name) values (4, 'disintermediate');
insert into artists (cus_event_id, name) values (5, 'Up-sized');
insert into artists (cus_event_id, name) values (6, 'multi-state');
insert into artists (cus_event_id, name) values (6, 'Enterprise-wide');
insert into artists (cus_event_id, name) values (7, 'Synchronised');
insert into artists (cus_event_id, name) values (7, 'Virtual');
insert into artists (cus_event_id, name) values (7, 'help-desk');
insert into artists (cus_event_id, name) values (7, 'stable');
insert into artists (cus_event_id, name) values (8, 'encryption');
insert into artists (cus_event_id, name) values (8, 'project');
insert into artists (cus_event_id, name) values (8, 'methodology');
insert into artists (cus_event_id, name) values (9, 'Graphical User Interface');
insert into artists (cus_event_id, name) values (8, 'focus group');
insert into artists (cus_event_id, name) values (9, 'content-based');
insert into artists (cus_event_id, name) values (2, 'upward-trending');
